upload_max_filesize=100M
post_max_size=100M
memory_limit=1024M
max_execution_time=300
max_input_vars=3000
max_input_time=300
date.timezone=Asia/Ho_Chi_Minh

; Disable OPcache completely for manual debug
opcache.enable=0
opcache.validate_timestamps=1
opcache.revalidate_freq=0
; Additional debug settings
display_errors=1
display_startup_errors=1
error_reporting=E_ALL
